### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by noborus** [noborus/guesswidth#13]
A panic occurred in trdsql.

```error
panic: runtime error: slice bounds out of range [77:76]

goroutine 1 [running]:
github.com/noborus/guesswidth.split({0xc000028a50, 0x4c}, {0xc00001ea40?, 0x7, 0x8}, 0x1)
        /go/src/github.com/noborus/guesswidth/guesswidth.go:282 +0x409
github.com/noborus/guesswidth.(*GuessWidth).Read(0xc00007e700)
        /go/src/github.com/noborus/guesswidth/guesswidth.go:179 +0xa5
github.com/noborus/trdsql.NewGWReader({0x202e8858c78, 0xc000033d90}, 0xc00005e060)
        /go/src/github.com/noborus/trdsql/input_gw.go:38 +0x108
github.com/noborus/trdsql.glob..func8({0x202e8858c78?, 0xc000033d90?}, 0x5?)
        /go/src/github.com/noborus/trdsql/reader.go:51 +0x1d
github.com/noborus/trdsql.NewReader({0x202e8858c78, 0xc000033d90}, 0xc00005e060)
        /go/src/github.com/noborus/trdsql/reader.go:239 +0x69
github.com/noborus/trdsql.ImportFileContext({0xc9dc88, 0x107b660}, 0xc0000603c0, {0xa69c08?, 0xb16280?}, 0x107b660?)
        /go/src/github.com/noborus/trdsql/importer.go:249 +0x18c
github.com/noborus/trdsql.(*ReadFormat).ImportContext(0xc00004e628, {0xc9dc88, 0x107b660}, 0x5f?, {0xc0000201e0, 0x1b})
        /go/src/github.com/noborus/trdsql/importer.go:101 +0x165
github.com/noborus/trdsql.(*TRDSQL).ExecContext(0xc00007dda0, {0xc9dc88, 0x107b660}, {0xc0000201e0, 0x1b})
        /go/src/github.com/noborus/trdsql/trdsql.go:178 +0x1e5
github.com/noborus/trdsql/cmd.Cli.Run({{0xc9a840?, 0xc00004e030?}, {0xc9a840?, 0xc00004e038?}}, {0xc00007e000, 0x6, 0x8})
        /go/src/github.com/noborus/trdsql/cmd/cmd.go:309 +0x26d0
main.main()
        /go/src/github.com/noborus/trdsql/cmd/trdsql/main.go:14 +0x45
```

[tasklist.txt](https://github.com/user-attachments/files/18257249/tasklist.txt)

**Comment by noborus** [comment]
It had already been fixed.
